# Generated by Django 6.0.6 on 2026-06-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('move', 'Move'), ('folder_create', 'Folder created'), ('folder_delete', 'Folder deleted')], max_length=32),
        ),
    ]
