# Generated by Django 6.0.6 on 2026-06-12 16:58

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kdf_iterations",
            field=models.PositiveIntegerField(default=600000),
        ),
        migrations.AddField(
            model_name="user",
            name="kdf_salt",
            field=models.CharField(
                default=apps.accounts.models.generate_kdf_salt,
                editable=False,
                max_length=64,
            ),
        ),
    ]
