# Generated by Django 6.0.6 on 2026-06-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_kdf_iterations_user_kdf_salt"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="storage_quota",
            field=models.BigIntegerField(default=16106127360),
        ),
    ]
