# Generated by Django 6.0.6 on 2026-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_storage_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enc_verifier',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='enc_verifier_nonce',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
